create table tb_grupo (id_grupo bigint not null auto_increment, ds_descricao varchar(255), ds_nome varchar(255), primary key (id_grupo))
create table tb_permissao (id_permissao bigint not null auto_increment, ds_descricao varchar(255), ds_permissao varchar(255), primary key (id_permissao))
create table tb_usuario (id_usuario bigint not null auto_increment, fl_ativo bit, ds_cidade varchar(255), ds_data_nasc varchar(255), ds_estado varchar(255), ds_login varchar(255), ds_nome varchar(255), ds_senha varchar(255), primary key (id_usuario))
create table tb_permissao_x_grupo (id_grupo bigint not null, id_permissao bigint not null)
create table tb_usuario_x_grupo (id_usuario bigint not null, id_grupo bigint not null)
alter table tb_permissao_x_grupo add constraint FK1urvbnxmsii7l4spsdl4gcah5 foreign key (id_permissao) references tb_permissao (id_permissao)
alter table tb_permissao_x_grupo add constraint FKf0wxoddgctu8vmf4vvbn48ufi foreign key (id_grupo) references tb_grupo (id_grupo)
alter table tb_usuario_x_grupo add constraint FKk111a4hed6rxsx29i1ifcuoub foreign key (id_grupo) references tb_grupo (id_grupo)
alter table tb_usuario_x_grupo add constraint FK74jm1ujfn8g162e11euowof58 foreign key (id_usuario) references tb_usuario (id_usuario)
